name: 01 - Building Blocks
on:
  #Trigger on every push to the repository
  push:
  #Allow manual truggering from the Github Actions UI
  workfllow_dispatch:
jobs:
  #First job :echo-hello
  echo-hello:
   runs-on: ubuntu-latest
   steps:
    - name: Say hello #Single step to print "Hello, World!"
      run: echo "Hello, World!"

  #Second job: echo-goodbye
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
    #First step: Failed step (will exit with non-zero code)
    - name: Failed step
      run:|
       echo "I will fail"
       exit 1 #Exits with a non-zero code, causing the step and job to fail
    #Second step : Say goodbye
    - name: Say goodbye
     run: echo "Goodbye!" 
