name: 02-workflow-events

on:
  push:

jobs:
  echo:
    runs-on: ububtu-latest
    steps:
      - name: Show the trigger
        run: echo "The workflow was triggered by a:${{github.event_name}}"
      
    
  
